spring:
  application:
    name: transactions-api

  profiles:
    active: dev   #Default profile Local

  r2dbc:
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger